packages:
  - apps/*
  - packages/*
  - configs/*
  - content

catalog:
  '@ai-sdk/gateway': 3.0.27
  '@ai-sdk/openai': 3.0.21
  '@ai-sdk/provider': 3.0.5
  '@ai-sdk/provider-utils': 4.0.10
  '@auth/core': 0.41.1
  '@auth/drizzle-adapter': 1.11.1
  '@biomejs/biome': 2.3.13
  '@changesets/cli': 2.29.8
  '@convex-dev/better-auth': 0.10.10
  '@kubb/cli': 4.19.2
  '@kubb/core': 4.19.2
  '@kubb/oas': 4.19.2
  '@kubb/plugin-client': 4.19.2
  '@kubb/plugin-mcp': 4.19.2
  '@kubb/plugin-oas': 4.19.2
  '@kubb/plugin-ts': 4.19.2
  '@kubb/plugin-zod': 4.19.2
  '@kubb/react': 4.3.1
  '@kubb/react-fabric': 0.12.6
  '@mcpauth/auth': 0.1.4
  '@modelcontextprotocol/sdk': 1.25.3
  '@next/third-parties': 16.1.6
  '@openapi-codegen/cli': 3.1.0
  '@openapi-codegen/typescript': 11.1.0
  '@radix-ui/react-avatar': 1.1.11
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toast': 1.2.15
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/typography': 0.5.19
  '@types/json-schema': 7.0.15
  '@types/node': 25.1.0
  '@types/pg': 8.16.0
  '@types/qrcode': 1.5.6
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  '@types/vscode': 1.108.1
  '@vercel/config': 0.0.28
  '@vercel/oidc': 3.1.0
  '@vscode/vsce': 3.7.1
  ai: 6.0.59
  better-auth: 1.4.18
  bunchee: 6.9.4
  case: 1.6.3
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  convex: 1.31.6
  dotenv: 17.2.3
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  es-module-lexer: 2.0.0
  framer-motion: 12.29.2
  geist: 1.5.1
  gray-matter: 4.0.3
  is-tree-shakable: 0.4.2
  jszip: 3.10.1
  knip: 5.82.1
  lefthook: 2.0.16
  lucide-react: 0.563.0
  markdown-to-jsx: 9.6.1
  mcp-handler: 1.0.7
  mintlify: 4.2.305
  next: 16.1.6
  next-auth: 5.0.0-beta.29
  next-intl: 4.8.0
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  openapi3-ts: 4.5.0
  pg: 8.17.2
  postcss: 8.5.6
  qrcode: 1.5.4
  react: 19.2.4
  react-dom: 19.2.4
  rimraf: 6.1.2
  rollup: 4.57.0
  stripe: 20.3.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  ts-morph: 27.0.2
  tsx: 4.21.0
  turbo: 2.8.0
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  vitest: 4.0.18
  zod: 4.3.6

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - lefthook
