packages:
  - apps/*
  - packages/*
  - configs/*
catalog:
  "@ai-sdk/provider": ^2.0.0
  "@changesets/cli": ^2.27.1
  "@next/eslint-plugin-next": ^14.1.4
  "@types/node": ^20.11.24
  "@types/react": ^18.2.61
  "@types/react-dom": ^18.2.19
  "@typescript-eslint/eslint-plugin": ^7.1.0
  "@typescript-eslint/parser": ^7.1.0
  "@vercel/oidc": ^3.0.3
  "@vercel/style-guide": ^5.2.0
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.0.0
  eslint-plugin-only-warn: ^1.1.0
  next: ^14.1.1
  prettier: ^3.2.5
  react: ^18.2.0
  react-dom: ^18.2.0
  tsup: ^8.0.2
  turbo: ^2.6.0
  typescript: 5.5.4
