packages:
  - apps/*
  - packages/*
  - configs/*
  - content

catalog:
  '@ai-sdk/gateway': ^3.0.2
  '@ai-sdk/provider': ^3.0.0
  '@ai-sdk/provider-utils': ^4.0.1
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': ^2.29.8
  '@next/third-parties': ^16.1.1
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-slot': ^1.2.4
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/typography': ^0.5.19
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vercel/config': ^0.0.24
  '@vercel/oidc': ^3.0.5
  ai: ^6.0.3
  bunchee: ^6.5.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.5.0
  framer-motion: ^12.23.26
  geist: ^1.5.1
  gray-matter: ^4.0.3
  is-tree-shakable: ^0.4.2
  knip: ^5.78.0
  lefthook: ^2.0.13
  lucide-react: ^0.562.0
  markdown-to-jsx: ^9.5.0
  mintlify: ^4.2.255
  next: ^16.1.1
  next-themes: ^0.4.6
  postcss: ^8.5.6
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  turbo: ^2.7.2
  typescript: ^5.9.3
  vitest: ^3.2.2

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - lefthook
