packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@ai-sdk/provider': ^3.0.0
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': ^2.29.8
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/sprintf-js': ^1.1.4
  '@types/turndown': ^5.0.6
  '@vercel/oidc': ^3.0.5
  ai: ^6.0.3
  diff: ^8.0.2
  esbuild: ^0.27.2
  knip: ^5.41.1
  minimatch: ^10.1.1
  next: ^16.1.1
  react: ^19.2.3
  react-dom: ^19.2.3
  sprintf-js: ^1.1.3
  tsup: ^8.5.1
  turbo: ^2.7.2
  turndown: ^7.2.2
  typescript: ^5.9.3
  vitest: ^4.0.16
  zod: ^4.2.1
