import { type BoothLayout, LAYOUT_SCHEMA_VERSION } from "./types";

/**
 * Built-in photobooth presets seeded into the `presets` table. Each entry's
 * `layout` omits the `id` (filled from the preset id at seed time). All slot and
 * text positions are normalized 0..1 of the canvas.
 */
export interface BuiltinPreset {
	id: string;
	name: string;
	shotCount: number;
	layout: Omit<BoothLayout, "id">;
}

export const BUILTIN_PRESETS: BuiltinPreset[] = [
	{
		id: "strip_3bw_vertical",
		name: "3-Photo B&W Strip",
		shotCount: 3,
		layout: {
			version: LAYOUT_SCHEMA_VERSION,
			kind: "strip_vertical",
			aspectRatio: 3.2,
			background: { type: "color", color: "#ffffff" },
			filter: "bw",
			photoSlots: [
				{
					id: "slot-1",
					x: 0.05,
					y: 0.02,
					width: 0.9,
					height: 0.285,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-2",
					x: 0.05,
					y: 0.357,
					width: 0.9,
					height: 0.285,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-3",
					x: 0.05,
					y: 0.695,
					width: 0.9,
					height: 0.285,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
			],
			textLayers: [
				{
					id: "text-names",
					content: "{coupleNames}",
					x: 0.0,
					y: 0.925,
					width: 0.55,
					rotation: -90,
					fontFamily: "Dancing Script",
					fontSize: 0.07,
					fontWeight: "bold",
					fontStyle: "normal",
					color: "#000000",
					align: "center",
					letterSpacing: 0.001,
					lineHeight: 1.2,
					opacity: 1,
				},
				{
					id: "text-date",
					content: "{date}",
					x: 0.75,
					y: 0.925,
					width: 0.55,
					rotation: -90,
					fontFamily: "Dancing Script",
					fontSize: 0.05,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#444444",
					align: "center",
					letterSpacing: 0.001,
					lineHeight: 1.2,
					opacity: 1,
				},
			],
			graphicLayers: [],
			print: {
				paperSize: "2x6_strip",
				orientation: "portrait",
				dpi: 300,
				bleedMm: 0,
				copies: 2,
			},
		},
	},
	{
		id: "strip_4cut_2col",
		name: "4-Cut Korean Strip",
		shotCount: 4,
		layout: {
			version: LAYOUT_SCHEMA_VERSION,
			kind: "strip_2col",
			aspectRatio: 1.45,
			background: { type: "color", color: "#fdf6e3" },
			filter: "none",
			photoSlots: [
				{
					id: "slot-1",
					x: 0.04,
					y: 0.04,
					width: 0.45,
					height: 0.44,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.005,
					cornerRadius: 0.01,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-2",
					x: 0.51,
					y: 0.04,
					width: 0.45,
					height: 0.44,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.005,
					cornerRadius: 0.01,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-3",
					x: 0.04,
					y: 0.5,
					width: 0.45,
					height: 0.44,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.005,
					cornerRadius: 0.01,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-4",
					x: 0.51,
					y: 0.5,
					width: 0.45,
					height: 0.44,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.005,
					cornerRadius: 0.01,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
			],
			textLayers: [
				{
					id: "text-names",
					content: "{coupleNames}  ·  {date}",
					x: 0.05,
					y: 0.955,
					width: 0.9,
					rotation: 0,
					fontFamily: "Dancing Script",
					fontSize: 0.045,
					fontWeight: "bold",
					fontStyle: "normal",
					color: "#7c5b3a",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
			],
			graphicLayers: [],
			print: {
				paperSize: "selphy_postcard",
				orientation: "portrait",
				dpi: 300,
				bleedMm: 0,
				copies: 1,
			},
		},
	},
	{
		id: "grid_2x2_postcard",
		name: "2×2 Grid Postcard",
		shotCount: 4,
		layout: {
			version: LAYOUT_SCHEMA_VERSION,
			kind: "grid_2x2",
			aspectRatio: 1.48,
			background: { type: "color", color: "#1a1a1a" },
			filter: "none",
			photoSlots: [
				{
					id: "slot-1",
					x: 0.03,
					y: 0.03,
					width: 0.455,
					height: 0.435,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0.008,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-2",
					x: 0.515,
					y: 0.03,
					width: 0.455,
					height: 0.435,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0.008,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-3",
					x: 0.03,
					y: 0.48,
					width: 0.455,
					height: 0.435,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0.008,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-4",
					x: 0.515,
					y: 0.48,
					width: 0.455,
					height: 0.435,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: null,
					borderWidth: 0,
					cornerRadius: 0.008,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
			],
			textLayers: [
				{
					id: "text-names",
					content: "{coupleNames}",
					x: 0.05,
					y: 0.935,
					width: 0.9,
					rotation: 0,
					fontFamily: "Great Vibes",
					fontSize: 0.06,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#ffffff",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
				{
					id: "text-date",
					content: "{date}",
					x: 0.05,
					y: 0.965,
					width: 0.9,
					rotation: 0,
					fontFamily: "Noto Serif",
					fontSize: 0.032,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#aaaaaa",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
			],
			graphicLayers: [],
			print: {
				paperSize: "selphy_postcard",
				orientation: "portrait",
				dpi: 300,
				bleedMm: 0,
				copies: 1,
			},
		},
	},
	{
		id: "strip_3_branded",
		name: "3-Photo Branded Strip",
		shotCount: 3,
		layout: {
			version: LAYOUT_SCHEMA_VERSION,
			kind: "strip_vertical",
			aspectRatio: 3.5,
			background: {
				type: "gradient",
				stops: [
					{ color: "#0f0c29", offset: 0 },
					{ color: "#302b63", offset: 0.5 },
					{ color: "#24243e", offset: 1 },
				],
				angle: 160,
			},
			filter: "none",
			photoSlots: [
				{
					id: "slot-1",
					x: 0.06,
					y: 0.03,
					width: 0.88,
					height: 0.26,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.004,
					cornerRadius: 0.015,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-2",
					x: 0.06,
					y: 0.315,
					width: 0.88,
					height: 0.26,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.004,
					cornerRadius: 0.015,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
				{
					id: "slot-3",
					x: 0.06,
					y: 0.6,
					width: 0.88,
					height: 0.26,
					rotation: 0,
					fit: "cover",
					filterOverride: null,
					borderColor: "#ffffff",
					borderWidth: 0.004,
					cornerRadius: 0.015,
					cropOffsetX: 0,
					cropOffsetY: 0,
					cropScale: 1,
				},
			],
			textLayers: [
				{
					id: "text-names",
					content: "{coupleNames}",
					x: 0.05,
					y: 0.875,
					width: 0.9,
					rotation: 0,
					fontFamily: "Great Vibes",
					fontSize: 0.08,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#ffd700",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
				{
					id: "text-date",
					content: "{date}",
					x: 0.05,
					y: 0.935,
					width: 0.9,
					rotation: 0,
					fontFamily: "Noto Serif",
					fontSize: 0.038,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#cccccc",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
				{
					id: "text-brand",
					content: "{eventName}",
					x: 0.05,
					y: 0.965,
					width: 0.9,
					rotation: 0,
					fontFamily: "Noto Serif",
					fontSize: 0.028,
					fontWeight: "normal",
					fontStyle: "normal",
					color: "#888888",
					align: "center",
					letterSpacing: 0.002,
					lineHeight: 1.2,
					opacity: 1,
				},
			],
			graphicLayers: [],
			print: {
				paperSize: "2x6_strip",
				orientation: "portrait",
				dpi: 300,
				bleedMm: 0,
				copies: 2,
			},
		},
	},
];
